### ISSUE TITLE
Having handleTextChange fire an action creator

### ISSUE THREAD

**Issue by YannickLeRoux** [EQuimper/react-native-google-autocomplete#13]
I want to keep track of the user input in `<TextInput> `inside my app store ? The `onChangeText` prop is already bind to `handleTextChange`.
Is there a way I can overwrite or extend the  `handleTextChange` method so I can call an action creator as the user types in ?

**Comment by EQuimper** [comment]
maybe you can use the arrow function in the props ?

```
onChangeText={(text) => {
  handleTextChange(text);
  myAction(text)
}}
```

**Comment by EQuimper** [comment]
but yes I can create a props where I can let you pass function in it and they will receive the text in it. If you think that can help. Something like 

```
textAction={myAction}
```

and myAction will receive also the text int it

**Comment by YannickLeRoux** [comment]
Using an arrow function worked well for me. Thank you very much
