### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by dancomanlive** [EQuimper/react-native-google-autocomplete#16]
The search results are not specific at all. Residential addresses are not found and search results are not based on proximity! Is there away to get specific search results?

![screen shot 2018-12-20 at 3 46 22 pm](https://user-images.githubusercontent.com/16872821/50271038-748fb700-046e-11e9-988a-7547a8d8b518.png)

**Comment by dancomanlive** [comment]
OK I found queryTypes='establishment' :D

**Comment by EQuimper** [comment]
Hey sorry didnt see the message. Nice catch
