### ISSUE TITLE
Search museums, restaurants ...

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [EQuimper/react-native-google-autocomplete#18]
Hello, thank you for this wonderful library ...
Would it be possible instead of looking for streets to search for places of interest such as museums, restaurants ...?
How could I integrate it with redux-form, I've tried with your example but it does not work?

**Comment by EQuimper** [comment]
You can change address for the places you want here https://github.com/EQuimper/react-native-google-autocomplete#props in the queryTypes for establishment

**Comment by JorgeMoralesLopez** [comment]
Thanks, radius does not work? I know that 50000 meters is the maximum, but it does not work for me.

      ```
<GoogleAutoComplete 
                apiKey={API_KEY} 
                debounce={500} 
                minLength={3} 
                language="es" 
                queryTypes='establishment' 
                //location='37.1848024, -5.7753099'
                radius="35000"
                components='country:es'
            >
                {({ handleTextChange, locationResults, fetchDetails, isSearching, inputValue, clearSearchs }) => (
                    <React.Fragment>
                    <View style={styles.inputWrapper}>
                        <Field 
                            name="nameRestaurant" 
                            component={FieldInput} 
                            placeholder="Nombre del restaurante" 
                            underlineColorAndroid='#fff' 
                            onChange={handleTextChange}
                            value={inputValue}    
                        />
                    </View>
                    {isSearching && <ActivityIndicator size="large" color="red" />}
                    <ScrollView style={{paddingHorizontal: 10}}>
                        {locationResults.map(el => (
                            <LocationItem 
                                key={el.id}
                                {...el}
                                fetchDetails={fetchDetails}
                            
                            />
                        ))}
                    </ScrollView>
                    </React.Fragment>
                )}
            </GoogleAutoComplete>
```

**Comment by JorgeMoralesLopez** [comment]
I have seen your video, how could I do so when clicking on the scrollView items that the result was put in the TextInput?

**Comment by YeonwooSung** [comment]
@JorgeMoralesLopez I made an arrow function

**Comment by EQuimper** [comment]
You will need to manage it with your state, or any kind of tool to keep track of the data. The library is really just an api call who give you access to the result. You can do all the stuff you want after that.

**Comment by JorgeMoralesLopez** [comment]
Thanks everything works well, what I am unable to operate is the radius, so that things that are very far away do not appear...

**Comment by zapcriativo** [comment]
Hi 

How do you search for address establishments at the same time?

Regards
