### ISSUE TITLE
How to handle two autocompleteInputValues in same component?

### ISSUE THREAD

**Issue by shane-peiris** [EQuimper/react-native-google-autocomplete#21]
Hi,

Thank you for this great package. Currently, I'm having a pick-up and drop-off textinputs with the google auto complete. But how do I achieve this task? 

Thank you in advance for your help.

Cheers!

**Comment by shane-peiris** [comment]
What I actually meant was how to handle each autocomplete task separately using one LocationItem component. I'm very new to react-native so appreciate your help on this.

**Comment by EQuimper** [comment]
@shane-peiris Sorry just see this, you closed it ? That mean you find an answer ?
