### ISSUE TITLE
Clear the locationResults when all text is erased

### ISSUE THREAD

**Issue by manurana** [EQuimper/react-native-google-autocomplete#3]
Great library ! Love the simplicity.

Any way to have the `locationResults` array cleared up when all text is erased ? For example using the `clear` method on the `Textinput`

**Comment by EQuimper** [comment]
@manurana Thank you, yes I will check this out tonight. Really good idea I didn't think about it :)

**Comment by EQuimper** [comment]
Done :) now you have access to `clearSearchs` from the render props :)
