### ISSUE TITLE
Cannot change the queryType to (cities)

### ISSUE THREAD

**Issue by irokhes** [EQuimper/react-native-google-autocomplete#6]
Hi,

I'm trying to change the queryType to cities but it does not work (or at least I don't know how to do it)

I've tried 

<GoogleAutoComplete apiKey="" debounce={300} minLength={3} queryType='(cities)'>

<GoogleAutoComplete apiKey="" debounce={300} minLength={3} queryType='cities'>

No luck at all! 

any idea?

Thanks

**Comment by EQuimper** [comment]
Gonna try it tonight. I came back to you when I figure out the problem :)

**Comment by EQuimper** [comment]
Can you give it a shot @irokhes :) I think that would work now
