### ISSUE TITLE
How can get postal code?

### ISSUE THREAD

**Issue by blackstar217** [EQuimper/react-native-google-autocomplete#7]
how can get postal code?

**Comment by EQuimper** [comment]
You can get the postal code from the detail query. If you look here https://youtu.be/UFiTL8lAktU?t=16m22s you can get it in the address_components

**Comment by EQuimper** [comment]
Did that work @blackstar217 ?

**Comment by EdisonDevadoss** [comment]
Hai,
@EQuimper I watched your video I got address_compents but in the address_compents postal code is not available. 
Help me.
![Screenshot from 2019-04-02 12-56-34](https://user-images.githubusercontent.com/30063304/55383895-e6d06700-5546-11e9-829f-94d8780474a1.png)

**Comment by EQuimper** [comment]
@EdisonDevadoss this is from the details fetch ?
