### ISSUE TITLE
How to increase the search results?

### ISSUE THREAD

**Issue by psalm00171** [EQuimper/react-native-google-autocomplete#8]

**Comment by EQuimper** [comment]
You mean the number of results ?

**Comment by psalm00171** [comment]
yes. i tried fiddling with the library just last week, i was trying to increase the number of suggested places, but still no luck

**Comment by EQuimper** [comment]
Yes, I don't even know how we can do this, this is the way google give me the response from the api. I'm gonna search for this and gonna find a solution. I will upload it there when done :)

**Comment by psalm00171** [comment]
Thank you

**Comment by EQuimper** [comment]
This is what I found for now https://developers.google.com/places/web-service/autocomplete#place_autocomplete_responses Look like 5 is the max. I try to check if we can maybe use pageToken and go further :)

**Comment by EQuimper** [comment]
https://stackoverflow.com/a/10089238/5670861

**Comment by psalm00171** [comment]
yes, i've also have read the documentation, and looks like pageToken is a way to get the other results. I'm also trying to integrate it.

**Comment by EQuimper** [comment]
PageToken dont look like work on autoComplete query :s

**Comment by psalm00171** [comment]
it just get the next page of result. looks like 5 will be the max result
